data_prep:
  version: "1.0"
  dataset_name: "machine_failure_prediction"
  columns_to_remove: ["id", "f_27"]
  outlier_features: []  # No outlier capping for experiment 3
  target_column: "target"
  outlier_method: "none"
  
feature_prep:
  apply_scaling: false  # Random Forest handles mixed scales naturally

model_evaluation:
  split_ratio: 0.2
  cross_validation_folds: 5
  evaluation_metric: "pr_auc"
  random_seed: 42

model:
  model_type: "random_forest"
  model_params:
    n_estimators: 200
    class_weight: "balanced"  # Key change for better failure detection
    max_depth: 12
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42



