data_prep:
  version: "1.0"
  dataset_name: "machine_failure_prediction"
  columns_to_remove: ["id", "f_27"]
  outlier_features: ["f_20", "f_06", "f_00"]
  target_column: "target"
  outlier_method: "quantile"  # Use quantile-based capping (q95/q05)
  
feature_prep:
  apply_scaling: false  # RF+KNN ensemble handles scaling internally

model_evaluation:
  split_ratio: 0.2
  cross_validation_folds: 5
  evaluation_metric: "pr_auc"
  random_seed: 42

model:
  model_type: "rf_knn_ensemble"
  model_params:
    rf_params:
      n_estimators: 100
      random_state: 42
    knn_params:
      n_neighbors: 11
      weights: "distance"
      metric: "manhattan"
    voting: "soft"
    weights: [1, 1]  # Equal weights for RF and KNN



