data_prep:
  version: "1.0"
  dataset_name: "machine_failure_prediction"
  columns_to_remove: ["id", "f_27"]
  outlier_features: ["f_20", "f_06", "f_00"]
  target_column: "target"
  
feature_prep:
  apply_scaling: true

model_evaluation:
  split_ratio: 0.2
  cross_validation_folds: 5
  evaluation_metric: "pr_auc"
  random_seed: 42

model:
  model_type: "knn"
  model_params:
    n_neighbors: 11
    weights: "distance"
    metric: "manhattan"



